const Motherboard = {
  id: 0,
  name: "",
  price: 0,
  producer: "",
  producerCode: "",
  boardStandard: "",
  widthMM: 0,
  depthMM: 0,
  chipset: "",
  cpuSocket: "",
  supportedProcessors: "",
  raidController: "",
  memoryStandard: "",
  memoryConnectorType: "",
  memorySlotsCount: 0,
  supportedMemoryFreq: "",
  maxMemoryGB: 0,
  channelArchitecture: "",
  hasIntegratedGraphicsSupport: false,
  graphicsChipset: "",
  cardLinking: "",
  soundChipset: "",
  audioChannels: "",
  integratedNetworkCard: "",
  networkChipset: "",
  wirelessSupport: "",
  expansionSlots: "",
  driveConnectors: "",
  internalConnectors: "",
  rearPanelConnectors: "",
  includedAccessories: "",
};

export default Motherboard;
