const PowerSupply = {
  id: 0,
  name: "",
  price: 0,
  producer: "",
  description: "",
  producerCode: "",
  formFactor: "",
  powerW: 0,
  certificate: "",
  powerFactorCorrection: "",
  efficiencyRating: "",
  cooling: "",
  fanDiameterMM: 0,
  security: "",
  modularCabling: "",
  atX24Pin_20Plus4: 0,
  pciE8Pin_6Plus2: 0,
  pciE16Pin: 0,
  pciE8Pin: 0,
  pciE6Pin: 0,
  cpU8Pin_4Plus4: 0,
  cpU8Pin: 0,
  cpU4Pin: 0,
  sata: 0,
  molex: 0,
  heightMM: 0,
  widthMM: 0,
  depthMM: 0,
  hasLighting: false,
};

export default PowerSupply;
