const Storage = {
  id: 0,
  name: "",
  price: 0,
  producer: "",
  producerCode: "",
  description: "",
  type: "",
  model: "",
  formFactor: "",
  capacity: "",
  interface: "",
  thiccnessMM: 0,
  cacheMemory: "",
  noiseLevelDB: 0,
  rotatingSpeedRPM: 0,
  weightG: 0,
  radiator: false,
  memoryChipType: "",
  readSpeedMBs: 0,
  writeSpeedMBs: 0,
  readRandomIOPS: 0,
  writeRandomIOPS: 0,
  longevity: "",
  tbw: "",
  key: "",
  controler: "",
  hardwareEncryption: false,
};
export default Storage;
