const Case = {
  id: 0,
  name: "string",
  price: 0,
  producer: "string",
  producerCode: "string",
  color: "string",
  hasLightning: true,
  heightCM: 0,
  lengthCM: 0,
  widthCM: 0,
  weightKG: 0,
  caseType: "string",
  compatibility: "string",
  hasWindow: true,
  isMuted: true,
  maxGPULengthCM: 0,
  maxCoolingSystemHeightCM: 0,
  usbTwoCount: 0,
  usbThreeCount: 0,
  usbThreePointOneCount: 0,
  usbThreePointTwoCount: 0,
  usbTypeCCount: 0,
  usbTurboChargingCount: 0,
  hasMemoryCardReader: true,
  hasAudioPort: true,
  hasMicrophonePort: true,
  internalBaysTwoPointFiveInch: 0,
  internalBaysThreePointFiveInch: 0,
  externalBaysThreePointFiveInch: 0,
  externalBaysFivePointTwoFiveInch: 0,
  expansionSlots: 0,
  panelFront: "string",
  panelRear: "string",
  panelSide: "string",
  panelBottom: "string",
  panelTop: "string",
  powerSupply: "string",
  powerSupplyPower: 0,
  description: "string",
};

export default Case;
