const CpuCooling = {
  id: 0,
  name: "string",
  price: 0,
  producer: "string",
  producerCode: "string",
  mountingType: "string",
  colorElement: "string",
  heightMM: 0,
  widthMM: 0,
  depthMM: 0,
  weightGrams: 0,
  processorSocket: "string",
  maxTDPinW: 0,
  baseMaterial: "string",
  hasLighting: true,
  heatPipesCount: 0,
  heatPipeDiameterMM: 0,
  fanCount: 0,
  fanDiameterMM: 0,
  maxFanSpeedPerMin: 0,
  airflowCFM: 0,
  maxNoiseLevelinDBA: 0,
  lifespanHours: 0,
};

export default CpuCooling;
