const GraphicCard = {
  id: 0,
  name: "",
  price: 0,
  producer: "",
  producerCode: "",
  chipsetProducer: "",
  chipsetType: "",
  coreClockMHz: 0,
  boostClockMHz: 0,
  streamProcessors: 0,
  ropUnits: 0,
  textureUnits: 0,
  rtCores: 0,
  tensorCores: 0,
  hasDLSS3Support: false,
  connectorType: "",
  cardLengthMM: 0,
  cardLinking: "",
  resolution: "",
  recommendedPSUCapacityW: 0,
  hasLEDLighting: false,
  memorySizeGB: 0,
  memoryType: "",
  memoryBusWidthBits: 0,
  memoryClockMHz: 0,
  coolingType: "",
  fanCount: 0,
  dSub: 0,
  displayPortCount: 0,
  miniDisplayPort: 0,
  dvi: 0,
  hdmi: 0,
  usbc: 0,
  powerConnectors: "",
  description: "",
};

export default GraphicCard;
