const GraphicCard = {
  id: 0,
  name: "string",
  price: 0,
  producer: "string",
  producerCode: "string",
  chipsetProducer: "string",
  chipsetType: "string",
  coreClockMHz: 0,
  boostClockMHz: 0,
  streamProcessors: 0,
  ropUnits: 0,
  textureUnits: 0,
  rtCores: 0,
  tensorCores: 0,
  hasDLSS3Support: true,
  connectorType: "string",
  cardLengthMM: 0,
  cardLinking: "string",
  resolution: "string",
  recommendedPSUCapacityW: 0,
  hasLEDLighting: true,
  memorySizeGB: 0,
  memoryType: "string",
  memoryBusWidthBits: 0,
  memoryClockMHz: 0,
  coolingType: "string",
  fanCount: 0,
  dSub: 0,
  displayPortCount: 0,
  miniDisplayPort: 0,
  dvi: 0,
  hdmi: 0,
  usbc: 0,
  powerConnectors: "string",
  description: "string",
};

export default GraphicCard;
