const Motherboard = {
  id: 0,
  name: "string",
  price: 0,
  producer: "string",
  producerCode: "string",
  boardStandard: "string",
  widthMM: 0,
  depthMM: 0,
  chipset: "string",
  cpuSocket: "string",
  supportedProcessors: "string",
  raidController: "string",
  memoryStandard: "string",
  memoryConnectorType: "string",
  memorySlotsCount: 0,
  supportedMemoryFreq: "string",
  maxMemoryGB: 0,
  channelArchitecture: "string",
  hasIntegratedGraphicsSupport: true,
  graphicsChipset: "string",
  cardLinking: "string",
  soundChipset: "string",
  audioChannels: "string",
  integratedNetworkCard: "string",
  networkChipset: "string",
  wirelessSupport: "string",
  expansionSlots: "string",
  driveConnectors: "string",
  internalConnectors: "string",
  rearPanelConnectors: "string",
  includedAccessories: "string",
};

export default Motherboard;
