const Storage = {
  id: 0,
  name: "string",
  price: 0,
  producer: "string",
  producerCode: "string",
  description: "string",
  type: "string",
  model: "string",
  formFactor: "string",
  capacity: "string",
  interface: "string",
  thiccnessMM: 0,
  cacheMemory: "string",
  noiseLevelDB: 0,
  rotatingSpeedRPM: 0,
  weightG: 0,
  radiator: true,
  memoryChipType: "string",
  readSpeedMBs: 0,
  writeSpeedMBs: 0,
  readRandomIOPS: 0,
  writeRandomIOPS: 0,
  longevity: "string",
  tbw: "string",
  key: "string",
  controler: "string",
  hardwareEncryption: true,
};
export default Storage;
