const WaterCooling = {
  id: 0,
  name: "string",
  price: 0,
  producer: "string",
  producerCode: "string",
  intelCompatibility: "string",
  amdCompatibility: "string",
  lighting: "string",
  weightG: 0,
  radiatorSizeMM: 0,
  radiatorLengthMM: 0,
  radiatorWidthMM: 0,
  radiatorHeightMM: 0,
  fanCount: 0,
  fanDiameterMM: 0,
  maxFanSpeedRPM: 0,
  hasPWMControl: true,
  maxAirflowCFM: 0,
  maxNoiseLevelDBa: 0,
  fanConnector: "string",
  pumpConnector: "string",
  ledConnector: "string",
};

export default WaterCooling;
